CREATE TABLE [dbo].[AccountSession]
(
	[Id] INT NOT NULL PRIMARY KEY,
    [AccountId] INT NOT NULL,
    [Active] BIT NOT NULL ,
    [Created] DATETIME NOT NULL DEFAULT GETDATE(),
    [Expires] DATETIME NOT NULL DEFAULT GETDATE() + '01:00:00'
)
